name: Optimize Images
on:
  workflow_dispatch: # This brings the button back!

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true # Just shrink them, don't make a PR

      - name: Force Save to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Robot: Images Optimized"
